[package]
name = "raytracing_in_one_week"
author="Rafał Opiłowski <rafalopilowski1@outlook.com>"
version = "1.0.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand="0.8.4"
image = "0.23.14"

