[package]
name = "raytracing_in_one_week"
author="Rafał Opiłowski <rafalopilowski1@outlook.com>"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand="0.8.4"
rayon="1.5.1"

[profile.release]
debug = true